---
name: bump version
on:
  repository_dispatch:
    types: [ bump-generate-command ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate:
    uses: sdischer-sap/.workflows/.github/workflows/bump-version.yaml@latest
    secrets: inherit
