---
name: Command Dispatch
on:
  issue_comment:
    types: [ created, edited ]
jobs:
  slashCommandDispatch:
    uses: sdischer-sap/.workflows/.github/workflows/dispatch-slash-commands.yaml@latest
    secrets: inherit
